/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

/**
 *
 * @author HÀ NHƯ
 */
public class KetToan_GUI extends javax.swing.JPanel {

    /**
     * Creates new form KetToan_GUI
     */
    public KetToan_GUI() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_demTien = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jtf_tongTien = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jtf_ngayGio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtf_chechLech = new javax.swing.JTextField();
        jtf_maPhieu = new javax.swing.JTextField();
        jtf_nhanVien1 = new javax.swing.JTextField();
        jtf_nhanVien2 = new javax.swing.JTextField();
        jtf_tienMat = new javax.swing.JTextField();
        jtf_doanhThu = new javax.swing.JTextField();
        jtf_atm = new javax.swing.JTextField();
        jtf_tienLayRa = new javax.swing.JTextField();
        btn_ketToan = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chi tiết kiểm tiền", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 16))); // NOI18N

        tbl_demTien.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        tbl_demTien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "500.000", null, null},
                {"2", "200.000", null, null},
                {"3", "100.000", null, null},
                {"4", "50.000", null, null},
                {"5", "20.000", null, null},
                {"6", "10.000", null, null},
                {"7", "5.000", null, null},
                {"8", "2.000", null, null},
                {"9", "1.000", null, null},
                {"10", "500", null, null}
            },
            new String [] {
                "STT", "Mệnh giá", "Số lượng", "Tổng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_demTien);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setText("Tổng:");

        jtf_tongTien.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jtf_tongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtf_tongTien, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(53, Short.MAX_VALUE)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 16))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtf_ngayGio.setText("Ngày và giờ");
        jtf_ngayGio.setEnabled(false);
        jPanel2.add(jtf_ngayGio, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 30, 301, 32));

        jLabel2.setText("Mã phiếu:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 80, 168, 31));

        jLabel3.setText("Nhân viên 2:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 166, 168, 31));

        jLabel4.setText("Nhân viên 1: ");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 123, 168, 31));

        jLabel5.setText("Tiền mặt:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 209, 168, 31));

        jLabel6.setText("Doanh thu:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 258, 168, 31));

        jLabel7.setText("ATM:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 301, 168, 31));

        jLabel8.setText("Tiền lấy ra:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 344, 168, 31));

        jLabel9.setText("Chênh lệch: ");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 387, 168, 31));

        jtf_chechLech.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jtf_chechLech.setForeground(new java.awt.Color(255, 0, 0));
        jtf_chechLech.setText("0d");
        jtf_chechLech.setEnabled(false);
        jPanel2.add(jtf_chechLech, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 250, 30));

        jtf_maPhieu.setEnabled(false);
        jPanel2.add(jtf_maPhieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 250, 30));

        jtf_nhanVien1.setText("Mã nhân viên - Tên nhân viên");
        jtf_nhanVien1.setEnabled(false);
        jPanel2.add(jtf_nhanVien1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 250, 30));
        jPanel2.add(jtf_nhanVien2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 250, 30));

        jtf_tienMat.setEnabled(false);
        jPanel2.add(jtf_tienMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 250, 30));

        jtf_doanhThu.setEnabled(false);
        jPanel2.add(jtf_doanhThu, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 250, 30));

        jtf_atm.setEnabled(false);
        jPanel2.add(jtf_atm, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 250, 30));

        jtf_tienLayRa.setEnabled(false);
        jtf_tienLayRa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_tienLayRaActionPerformed(evt);
            }
        });
        jPanel2.add(jtf_tienLayRa, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 250, 30));

        btn_ketToan.setBackground(new java.awt.Color(0, 51, 255));
        btn_ketToan.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_ketToan.setText("Kết toán");
        btn_ketToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ketToanActionPerformed(evt);
            }
        });
        jPanel2.add(btn_ketToan, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 370, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Kết toán");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(471, 471, 471))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_tienLayRaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_tienLayRaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_tienLayRaActionPerformed

    private void btn_ketToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ketToanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ketToanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ketToan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtf_atm;
    private javax.swing.JTextField jtf_chechLech;
    private javax.swing.JTextField jtf_doanhThu;
    private javax.swing.JTextField jtf_maPhieu;
    private javax.swing.JTextField jtf_ngayGio;
    private javax.swing.JTextField jtf_nhanVien1;
    private javax.swing.JTextField jtf_nhanVien2;
    private javax.swing.JTextField jtf_tienLayRa;
    private javax.swing.JTextField jtf_tienMat;
    private javax.swing.JTextField jtf_tongTien;
    private javax.swing.JTable tbl_demTien;
    // End of variables declaration//GEN-END:variables
}
